runtime: python37

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: auto

env_variables:
  POSTGRESQL_CONNECTION_NAME: liquidswap-222219:us-central1:ls-db
  POSTGRES_DB: ls-db
  POSTGRES_PASSWORD: guvub7DCCrbAa9hd
  POSTGRES_USER: liquidswap
  POSTGRES_HOST: 35.194.13.156
  SERVER_SOFTWARE: Google App Engine

basic_scaling:
  max_instances: 2